# 108-夏 專題:高雄發大財  
> 鄧羽彤	蔡佩芸	蔡烜廷  

## 目錄  

[前置作業](#1)   
[清洗資料](#2)  
[資料視覺化](#3)  

<h2 id=1></h2>  
## 前置作業
### 導入套件  
```{r results ='hide',message =FALSE,warning=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(lubridate)
```

### 導入檔案  
```{r results ='hide',message =FALSE,warning=FALSE}
Tr18<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/Train2018.csv")
Tr19<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/Train2019.csv")

hsr<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/Taiwan High Speed Rail.csv")

H16_1<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10501.csv")
H16_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10502.csv")
H16_3<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10503.csv")
H16_4<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10504.csv")
H16_5<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10505.csv")
H16_6<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10506.csv")
H16_7<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10507.csv")
H16_8<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10508.csv")
H16_9<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10509.csv")
H16_10<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10510.csv")
H16_11<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10511.csv")
H16_12<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10512.csv")

H16_1_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10501_2.csv")
H16_2_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10502_2.csv")
H16_3_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10503_2.csv")
H16_4_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10504_2.csv")
H16_5_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10505_2.csv")
H16_6_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10506_2.csv")
H16_7_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10507_2.csv")
H16_8_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10508_2.csv")
H16_9_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10509_2.csv")
H16_10_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10510_2.csv")
H16_11_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10511_2.csv")
H16_12_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10512_2.csv")

H17_1<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10601.csv")
H17_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10602.csv")
H17_3<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10603.csv")
H17_4<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10604.csv")
H17_5<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10605.csv")
H17_6<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10606.csv")
H17_7<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10607.csv")
H17_8<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10608.csv")
H17_9<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10609.csv")
H17_10<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10610.csv")
H17_11<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10611.csv")
H17_12<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10612.csv")

H17_1_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10601_2.csv")
H17_2_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10602_2.csv")
H17_3_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10603_2.csv")
H17_4_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10604_2.csv")
H17_5_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10605_2.csv")
H17_6_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10606_2.csv")
H17_7_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10607_2.csv")
H17_8_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10608_2.csv")
H17_9_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10609_2.csv")
H17_10_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10610_2.csv")
H17_11_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10611_2.csv")
H17_12_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel16-17/file/10612_2.csv")

H18_1<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10701.csv")
H18_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10702.csv")
H18_3<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10703.csv")
H18_4<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10704.csv")
H18_5<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10705.csv")
H18_6<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10706.csv")
H18_7<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10707.csv")
H18_8<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10708.csv")
H18_9<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10709.csv")
H18_10<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10710.csv")
H18_11<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10711.csv")
H18_12<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10712.csv")
H19_1<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10801.csv")
H19_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10802.csv")
H19_3<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10803.csv")

H18_1_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10701-2.csv")
H18_2_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10702-2.csv")
H18_3_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10703-2.csv")
H18_4_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10704-2.csv")
H18_5_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10705-2.csv")
H18_6_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10706-2.csv")
H18_7_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10707-2.csv")
H18_8_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10708-2.csv")
H18_9_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10709-2.csv")
H18_10_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10710-2.csv")
H18_11_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10711-2.csv")
H18_12_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10712-2.csv")
H19_1_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10801-2.csv")
H19_2_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10802-2.csv")
H19_3_2<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/hotel/file/10803-2.csv")


sum<-read.csv("C:/users/chris/Documents/GitHub/Final-Topic__RICH/MemberA/sum.csv")
sum2<-read.csv('C:/users/chris/Documents/GitHub/Final-Topic__RICH/MemberA/sum2017-2018.csv')
sum3<-read.csv('C:/users/chris/Documents/GitHub/Final-Topic__RICH/MemberA/sum2016-2017.csv')
sum4<-read.csv('C:/users/chris/Documents/GitHub/Final-Topic__RICH/MemberA/sum2015-2016.csv')
```

<h2 id=2></h2>  
## 清洗資料
### 按日期、地點分類火車站進出人次
```{r}
Tr18 <- Tr18 %>%
  rename(In="進站", Out="出站") %>%
  mutate(year=BOARD_DATE%/%10000, month=(BOARD_DATE%/%100)%%100, day=BOARD_DATE%%100)
Tr18_KS<-filter(Tr18,177<TKT_BEG & TKT_BEG<189)

Tr19 <- Tr19 %>%
  rename(In="進站", Out="出站") %>%
  mutate(year=BOARD_DATE%/%10000, month=(BOARD_DATE%/%100)%%100, day=BOARD_DATE%%100)
Tr19_KS<-filter(Tr19,177<TKT_BEG & TKT_BEG<189)
```

### 加總高雄地區各月份火車站出、入站總人次
```{r}
Tr_Pass<-c()
for (i in 1:12){
  Mon<-filter(Tr18_KS,month==i)
  Tr_Pass[i]<-(sum(select(Mon,In))+sum(select(Mon,Out)))
}
for (i in 1:3){
  Mon<-filter(Tr19_KS,month==i)
  Tr_Pass[12+i]<-(sum(select(Mon,In))+sum(select(Mon,Out)))
}
```

### 加總高雄地區各月份高鐵站出、入站總人次
```{r}
hsr<- hsr %>%
  rename(In.Out="車站.進.出站", DATE="年度.月份") 

hsr$DATE<-gsub("年","-",hsr$DATE)
hsr$DATE<-gsub("月","",hsr$DATE)
hsr$DATE<-(str_split(hsr$DATE,"-"))
Count<-length(hsr$DATE)

for (i in 1:Count){
  Vec<-hsr$DATE[[i]]
  hsr$year[i]<-Vec[1]
  hsr$month[i]<-Vec[2]
}

hsr_Pass<-c()
for (i in 1:12){
  y2018<-filter(hsr,year==2018)
  month<-filter(y2018,month==i)
  hsr_Pass[i]<-(sum(select(month,"左營")))
  if (i<=6){
    y2019<-filter(hsr,year==2019)
    Month<-filter(y2019,month==i)
    hsr_Pass[12+i]<-(sum(select(Month,"左營")))
  }
}
```

### 整理高雄地區旅館收益資料、旅客分類資料
```{r}
hotel<-list(H18_1,H18_2,H18_3,H18_4,H18_5,H18_6,H18_7,H18_8,H18_9,
     H18_10,H18_11,H18_12,H19_1,H19_2,H19_3)
guest<-list(H18_1_2,H18_2_2,H18_3_2,H18_4_2,H18_5_2,H18_6_2,
      H18_7_2,H18_8_2,H18_9_2,H18_10_2,H18_11_2,H18_12_2,
      H19_1_2,H19_2_2,H19_3_2)

hotel_2<-list(H16_1,H16_2,H16_3,H16_4,H16_5,H16_6,H16_7,H16_8,H16_9,H16_10,H16_11,H16_12,
            H17_1,H17_2,H17_3,H17_4,H17_5,H17_6,H17_7,H17_8,H17_9,H17_10,H17_11,H17_12,
            H18_1,H18_2,H18_3,H18_4,H18_5,H18_6,H18_7,H18_8,H18_9,H18_10,H18_11,H18_12,
            H19_1,H19_2,H19_3)
guest_2<-list(H16_1_2,H16_2_2,H16_3_2,H16_4_2,H16_5_2,H16_6_2,H16_7_2,H16_8_2,H16_9_2,H16_10_2,H16_11_2,H16_12_2,
            H17_1_2,H17_2_2,H17_3_2,H17_4_2,H17_5_2,H17_6_2,H17_7_2,H17_8_2,H17_9_2,H17_10_2,H17_11_2,H17_12_2,
            H18_1_2,H18_2_2,H18_3_2,H18_4_2,H18_5_2,H18_6_2,H18_7_2,H18_8_2,H18_9_2,H18_10_2,H18_11_2,H18_12_2,
            H19_1_2,H19_2_2,H19_3_2)
```

### 加總各月份住房次數
```{r}
NRO<-c()
for (i in 1:15){
  H<-as.data.frame(hotel[i])
  NRO[i]<-sum(select(H,No..of.Rooms.Occupied))
}
```

## 加總各月份房租收入(3y)
```{r}
RR<-c()
for (i in 1:39){
  H<-as.data.frame(hotel_2[i])
  RR[i]<-sum(select(H,Room.Revenue))
}
```

### 加總各月份陸客住房次數(3y)
```{r}
china<-c()
for (i in 1:39){
  G<-as.data.frame(guest_2[i])
  china[i]<-sum(select(G,China))
}
```


### 加總各月份各國住房次數
```{r}
country<-list()

for (i in 1:15){
  G<-as.data.frame(guest[i])
  G<-select(G,-Hotel.Name,-Total.1,-Total)
  colSums(G)
  country[[i]]<-colSums(G)
}

```

<h2 id=3></h2>  
## 資料視覺化
### 高雄旅客人數變化折線圖(按台鐵、高鐵進出站人次和旅館住房數)
```{r}
table1<-data.frame(Category=rep(c("train","high_speed_rail*1.5",
                                  "hotel*37.5"),each=15),
                   Month=rep(c("18.1","18.2","18.3","18.4",
                               "18.5","18.6","18.7","18.8",
                               "18.9","18.10","18.11",
                               "18.12","19.1","19.2","19.3"
                               ),3),
                   Number=c(Tr_Pass[1:15],hsr_Pass[1:15]*1.5,NRO*37.5))

table1$Category<-factor(table1$Category,
                        levels=c("train","high_speed_rail*1.5",
                                   "hotel*37.5"),ordered=TRUE)
table1$Month<-factor(table1$Month,
                     levels=c("18.1","18.2","18.3","18.4",
                              "18.5","18.6","18.7","18.8",
                              "18.9","18.10","18.11",
                              "18.12","19.1","19.2","19.3"),
                     ordered=TRUE)
Line<-ggplot(data=table1,aes(x=Month,y=Number,group=Category))+
  geom_line(aes(color=Category))+
  geom_point(aes(color=Category))
print(Line)
```
  
### 旅館住房數圓餅圖(按旅客國籍)
```{r}
for (j in 10:15){
  VEC<-c(1:15)
  Country<-data.frame(country[[j]])
  RN<-row.names(Country)
  L<-length(RN)
  COUNTRY=c(country[[j]])
  
  table2<-data.frame(Category=RN,
                     COUNTRY=c(country[[j]]),
                     row.names=c(1:L))
  
  COU=cumsum(COUNTRY)
  midpoint=COU-COUNTRY/2
  per<-round(COUNTRY/sum(COUNTRY)*100,2)
  paste_num<-length(per)
  
  Lab<-list()
  lab<-c()
  for (i in 1:paste_num){
    if (per[i]<=5){
      Lab[[i]]<-paste0(" ")
    }
    else {
      Lab[[i]]<-paste0(per[i],"%")
    }
    lab[i]<-Lab[[i]]
  }
  Pie<-ggplot(table2,aes(x="",y=COUNTRY,fill=Category))+
    geom_bar(stat="identity")+
    coord_polar("y",start=0)+
    geom_text(aes(x=1,y=midpoint,label=lab))+
    ggtitle(paste0("No.",VEC[j]))
  print(Pie)
}
```

### 交通工具搭乘人次長條圖
```{r}
table3<-data.frame(Month=rep(c("18.1","18.2","18.3","18.4",
                               "18.5","18.6","18.7","18.8","18.9","18.10",
                               "18.11","18.12","19.1","19.2","19.3"),2),
                   Number=c(Tr_Pass,hsr_Pass[1:15]),
                   Category=factor(rep(c("train","high_speed_rail"),each=15)))
print(table3)

table3$Month<-factor(table3$Month,
                     levels=c("18.1","18.2","18.3","18.4",
                              "18.5","18.6","18.7","18.8","18.9","18.10",
                              "18.11","18.12","19.1","19.2","19.3"),
                     ordered=T)
Bar1<-ggplot(data=table3,aes(x=Month,y=Number,fill=Category)) +
  geom_bar(stat="identity")
print(Bar1)

Bar2<-ggplot(data=table3,aes(x=Month,y=Number,fill=Category)) +
  geom_bar(stat="identity",position="dodge")
print(Bar2)
```

### 火車每日進出佔總人次面積圖
```{r}
Tr_KS<-rbind(Tr18_KS,Tr19_KS)
Tr_KS<-Tr_KS %>%
  mutate(Num.=In+Out,Date=ymd(BOARD_DATE))
table4<-data.frame(Date=Tr_KS$Date,
                Num=Tr_KS$Num.,
                station=Tr_KS$STOP_NAME)
Area<-ggplot(table4,aes(x=Date,y=Num,fill=station))+
  geom_area(position="stack")+
  scale_x_date(date_breaks = "2 month")
print(Area)
```

### 準備資料
```{r}
YEAR<-c("Jan","Feb","Mar","Apr","May","Jun",
        "Jul","Aug","Sep","Oct","Nov","Dec")
thrYear<-rep(YEAR,3)
Month<-c(thrYear,"Jan","Feb","Mar")
Year<-c(rep(c("2016","2017","2018"),each=12),rep(c("2019"),3))
```

### 旅館近三年陸客住房數折線圖
```{r}
table5<-data.frame(Month=Month,
                   Year=Year,
                   Number=china)

table5$Month<-factor(table5$Month,
                     levels=c("Jan","Feb","Mar","Apr","May","Jun",
                              "Jul","Aug","Sep","Oct","Nov","Dec"),
                     ordered=TRUE)
Line2<-ggplot(data=table5,aes(x=Month,y=Number,group=Year))+
  geom_line(aes(color=Year))+
  geom_point(aes(color=Year))
print(Line2)

```

### 旅館近三年總收益長條圖
```{r}
table6<-data.frame(Month=Month,
                   Year=Year,
                   Revenue=RR)
table6$Month<-factor(table6$Month,
                     levels=c("Jan","Feb","Mar","Apr","May","Jun",
                              "Jul","Aug","Sep","Oct","Nov","Dec"),
                     ordered=TRUE)
Bar3<-ggplot(data=table6,aes(x=Month,y=RR,fill=Year)) +
  geom_bar(stat="identity",position="dodge")
print(Bar3)
```



### 高雄觀光遊客數2018-2019的統計圖表
```{r}
sum.1<- sum %>% 
  mutate(date = (paste(year,mon,day,sep="-") %>% ymd()))
Graph_sum<-ggplot(data=sum.1,aes(x=date,y=Number,group=Category))+
  geom_line(aes(color=Category))+
  geom_point(size = 4, shape = 22, colour = "darkred", fill = "lightblue")+
  scale_x_date(date_labels="%b %y",date_breaks  ="1 month")
print(Graph_sum)
```

### 高雄觀光遊客數2017-2018的統計圖表
```{r}
sum2.1<- sum2 %>% 
  mutate(date = (paste(year,mon,day,sep="-") %>% ymd()))
Graph_sum2<-ggplot(data=sum2.1,aes(x=date,y=Number,group=Category))+
  geom_line(aes(color=Category))+
  geom_point(size = 4, shape = 22, colour = "darkred", fill = "blue")+
  scale_x_date(date_labels="%b %y",date_breaks  ="1 month")
print(Graph_sum2)
```

### 高雄觀光遊客數2016-2017的統計圖表
```{r}
sum3.1<-sum3 %>%
  mutate(date = (paste(year,mon,day,sep="-") %>% ymd()))
Graph_sum3<-ggplot(data=sum3.1,aes(x=date,y=Number,group=Category))+
  geom_line(aes(color=Category))+
  geom_point(size = 4, shape = 22, colour = "darkred", fill = "green")+
  scale_x_date(date_labels="%b %y",date_breaks  ="1 month")
print(Graph_sum3)
```

### 高雄觀光遊客數2015-2016的統計圖表
```{r}
sum4.1<- sum4 %>% 
  mutate(date = (paste(year,mon,day,sep="-") %>% ymd()))
Graph_sum4<-ggplot(data=sum4.1,aes(x=date,y=Number,group=Category))+
  geom_line(aes(color=Category))+
  geom_point(size = 4, shape = 22, colour = "darkred", fill = "orange")+
  scale_x_date(date_labels="%b %y",date_breaks  ="1 month")
print(Graph_sum4)
```